# Generated by Django 4.2.5 on 2023-10-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('date_created', models.TextField()),
                ('timestamp', models.FloatField()),
            ],
            options={
                'db_table': 'entries',
            },
        ),
    ]
